### ISSUE TITLE
Comments and posts repeat themselves when scrolling.

### ISSUE THREAD

**Issue by frozenfire98** [moxi9/phpfox-v3-dist#7] opened 2015-10-09 19:19 UTC
On statuses, blogs, and feeds, when you have to scroll down to see more, things repeat themselves and duplicate. IE-

Comment/Post A
Comment/Post B
Comment/Post C
Comment/Post D
Comment/Post E
-> Comment/Post A
-> Comment/Post B
-> Comment/Post C
-> Comment/Post D
-> Comment/Post E
Comment/Post F
Comment/Post G

**Comment by Data66PF** [comment] 2015-10-09 19:30
I can reproduce this on her site. I cannot reproduce it on my sites but my sites are not as big as her site or as active. We might need to test on her site.

**Comment by hiwap3** [comment] 2015-11-03 00:21
please provide a fix for this bug.. alot people want continue to use phpfox v3!

**Comment by cybervang** [comment] 2015-12-13 22:29
Please help fix this. I've invested so much time, money and effort to this project just to end it on this serious bug. It's really frustrating. The posts repeat themselves and there's nothing I can do to solve this.

**Comment by cybervang** [comment] 2015-12-13 22:30
i can replicate this everytime.

No cache.
2 members only on SITE.

User 1 posts 1-10
User 2 posts 1-5

>User 1 posts 1-10
>User 2 posts 1-5

refresh and the bug clearly show's itself.

**Comment by cybervang** [comment] 2016-01-17 16:28
It's the AJAX FEED "TRUE" that is causing this I think.

**Comment by frozenfire98** [comment] 2016-01-17 19:56
If you're speaking of this- http://nimb.ws/aJ80Uo
Mine has always been set to false, as I was told Ajax could cause some issues when i first started getting my site set up :)

**Comment by cybervang** [comment] 2016-01-19 00:47
Unsure yet. Hopefully phpfox dev can solve this issue and let us know if it's that or if it's not.

**Comment by Data66PF** [comment] 2016-01-19 13:02
This is fixed for v4 and will be applied to test on the testing site we have.

**Comment by cybervang** [comment] 2016-02-23 17:56
Thank you Data66, I hope to see a solution to this on 3.x also. The ajax is causing this based on my test. Right now I guess I am using no AJAX at all just to be sure everything works. Kinda frustrated that this script is not ajax effective but rely solely on full page reloads to be update feeds to be stable. I really want to be able to enable ajax on the feeds.

**Comment by Data66PF** [comment] 2016-02-24 09:22
This is fixed in v3.9

**Closed** 2016-02-24 09:22 UTC
Labels: bug, Fixed
